### PR TITLE
Wingyfy_openresty module for puppet

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by leifg** [comment]
👎  Correct me if I'm wrong:

All you did was remove attribution and the license?

**Comment by ghost** [comment]
@leifg Hi, 

I am not sure, what has been done wrong. I was just trying to learn the GIT and GITHUB command as I am quite new in GIT. However I am in this github from more than 2 years but I am not very active member of this. I was trying to learn the commands like " git commit and git pull,  etc." and later I was trying to add and delete the contents from the code. 

I apologise If I have done anything wrong.

**Comment by ghost** [comment]
Ohh, I see now.  I am so so sorry. I tried to pull this request to my branch and then later I was trying to make modifications, however it happend (changes in codes) accidently to your master branch. 

Is there any way to revert this back. I am feeling too bad for what I have done. Please forgive me. I did a bad learning. :(

**Comment by leifg** [comment]
Don't worry it's not merged into master.

**Pull request closed without merging**
